// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditCall struct {
	ID        pgtype.UUID `json:"id"`
	Result    pgtype.Text `json:"result"`
	Exception pgtype.Text `json:"exception"`
	CreatedAt interface{} `json:"created_at"`
	UpdatedAt interface{} `json:"updated_at"`
}

type AuditOperation struct {
	OperationName string      `json:"operation_name"`
	CreatedAt     interface{} `json:"created_at"`
	UpdatedAt     interface{} `json:"updated_at"`
}
