// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"
)

const getAuditOperationByOperationName = `-- name: GetAuditOperationByOperationName :one
select 
    operation_name, created_at, updated_at
from audit_operation
where operation_name = $1
`

func (q *Queries) GetAuditOperationByOperationName(ctx context.Context, operationName string) (AuditOperation, error) {
	row := q.db.QueryRow(ctx, getAuditOperationByOperationName, operationName)
	var i AuditOperation
	err := row.Scan(&i.OperationName, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getAuditOperations = `-- name: GetAuditOperations :many
select
    operation_name, created_at, updated_at 
from audit_operation ao
`

func (q *Queries) GetAuditOperations(ctx context.Context) ([]AuditOperation, error) {
	rows, err := q.db.Query(ctx, getAuditOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditOperation
	for rows.Next() {
		var i AuditOperation
		if err := rows.Scan(&i.OperationName, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
