// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	GetAuditOperationByOperationName(ctx context.Context, operationName string) (AuditOperation, error)
	GetAuditOperations(ctx context.Context) ([]AuditOperation, error)
}

var _ Querier = (*Queries)(nil)
